### ISSUE TITLE
sampling time as a system property for CT and DT systems

### ISSUE THREAD

**Issue by seaveredge** [GerbenBeintema/deepSI#3]
The question is whether and how we define the property associated with the sampling time. For CT systems, this is only a property of the data that you feed to the system, and hence is only needed when you integrate the system using the e.g. RK4 method. For discrete-time system, you will not need the sampling-time in principle, as it defines the next step. However, when discretizing a CT model, the sampling time used in this discretization is definitely a system property!
In Matlab the CT models have the sampling time property (`sys.Ts`) defined as 0, while DT models have it defined as a positive number or -1 if undefined during creation of the object.

What are we considering for deepSI?

**Comment by GerbenBeintema** [comment]
Thanks for your suggestion, the current handling of sampling time has been ad hoc. Hence, I will probably change the implementation in the next major update of deepSI to 0.4.0 for this will probably break backward compatibility. 

I'm not entirely sure if the sampling time of the MATLAB is the most robust (e.g. changing sampling time between system data sets or inherently discrete-time system). But it is already better than the current implementation that is present in deepSI.
