### ISSUE TITLE
Error when saving system if directory does not exist

### ISSUE THREAD

**Issue by seaveredge** [GerbenBeintema/deepSI#5]
When I say `fit_sys.save_system(savefilename)`, with `savefilename` some path, which apparently did not exists, I get after training the following error:
```
| 96/100 [6:59:31<17:26, 261.69s/it]E
  File "C:\Users\chris\anaconda3\envs\deepSI\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\chris\anaconda3\envs\deepSI\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'stat_12DoF/res/velocity-noisydata-12DoF_D12042022-T1221'
```
Without your (@GerbenBeintema) help, it is extremely difficult to obtain the trained system. I think it is much more user-friendly to add in the save_system function a check whether the directory exists, and if not, make it, and then save it...

**Comment by GerbenBeintema** [comment]
Sorry to hear that you are having trouble with saving your models. In general, saving anything in python to a non-existing directory will not create a directory to reduce the unintended system-altering effects and hence deepSI will keep within this framework. 

However, you will still be able to recover your trained model for in section "4.4 Recovery of system after crash" of the ["Examples 1; The flow of deepSI.ipynb"](https://github.com/GerbenBeintema/deepSI/blob/master/examples/Examples%201%3B%20The%20flow%20of%20deepSI.ipynb) notebook which shows a recovery example in detail.
